version: '3'
services:
  my-app:
    container_name: my-app
    image: yusufabdulsttar/my-app
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false    
    depends_on:
      - mongo      

  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    depends_on:
    - my-app

volumes:
  mongo-db:
